management:
  tracing:
    sampling:
      probability: ${TRACING_SAMPLING_PROBABILITY:0.1}
    export:
      otlp:
        enabled: ${OTLP_TRACING_ENABLED:false}

logging:
  structured:
    format:
      console: ecs
    ecs:
      service:
        environment: ${APP_ENVIRONMENT:production}
